# Generated by Django 4.1 on 2023-05-23 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_offers_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
