# Generated by Django 4.1 on 2023-05-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_order_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.SlugField(default='some', editable=False, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordercategories',
            name='slug',
            field=models.SlugField(default='some', editable=False, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
